import Image from "next/image";
import Link from "next/link";
import { Badge } from "@/components/ui/Badge";
import { LinkButton } from "@/components/ui/Button";
import { SectionHeading } from "@/components/ui/SectionHeading";
import { experiences } from "@/data/experiences";
import { treks } from "@/data/treks";
import { tourCategories } from "@/data/tour-categories";
import { vehicleCategories } from "@/data/vehicle-categories";
import { valuePoints } from "@/data/why-trekphillic";

const heroImagePath = "/images/hero/hero-mountains.png";

export function Hero() {
  return <section className="hero-section relative isolate overflow-hidden bg-forest-deep text-white" id="hero"><div className="hero-image-layer"><Image alt="Himalayan mountains beneath an open sky" className="object-cover object-[58%_center]" fill priority sizes="100vw" src={heroImagePath} /></div><div className="hero-overlay" /><div className="hero-grid relative mx-auto grid min-h-[680px] max-w-6xl items-center px-6 py-20 lg:min-h-[720px] lg:px-10 lg:py-24"><div className="relative z-[1] max-w-2xl"><Badge>TRAVEL DEEPER • LIVE WILDER</Badge><h1 className="mt-7 max-w-xl text-6xl font-semibold leading-[0.96] tracking-[-0.06em] sm:text-8xl">Mountains<br />Are Calling.</h1><p className="mt-7 max-w-lg text-lg leading-8 text-white/80">Thoughtful Himalayan treks, tours, and road journeys for people who want to travel a little deeper.</p><div className="mt-9 flex flex-wrap gap-4"><LinkButton className="bg-white text-forest hover:bg-sage" href="/treks">Explore Treks</LinkButton><LinkButton className="border-white/35 text-white hover:border-white" href="/enquiry" variant="secondary">Plan Your Trip</LinkButton></div></div></div></section>;
}

export function TripPlanner() {
  return <section className="relative z-[2] mx-auto -mt-10 w-full max-w-5xl px-6 lg:px-10"><form className="grid gap-3 rounded-3xl border border-border bg-surface p-4 shadow-xl sm:grid-cols-[1fr_1fr_1fr_auto] sm:items-end sm:p-5" action="/enquiry" method="get"><label className="grid gap-2 px-2 text-xs font-semibold uppercase tracking-[0.12em] text-teal" htmlFor="planner-interest">I want to<select className="min-h-11 rounded-xl border border-border bg-background px-3 text-sm font-medium normal-case tracking-normal text-foreground outline-none focus:border-teal" defaultValue="" id="planner-interest" name="interest"><option disabled value="">Choose an experience</option><option value="trek">Find a trek</option><option value="tour">Plan a tour</option><option value="vehicle">Arrange a vehicle</option></select></label><label className="grid gap-2 px-2 text-xs font-semibold uppercase tracking-[0.12em] text-teal" htmlFor="planner-season">When<select className="min-h-11 rounded-xl border border-border bg-background px-3 text-sm font-medium normal-case tracking-normal text-foreground outline-none focus:border-teal" defaultValue="" id="planner-season" name="season"><option disabled value="">Choose a season</option><option value="summer">Summer</option><option value="monsoon">Monsoon</option><option value="winter">Winter</option></select></label><label className="grid gap-2 px-2 text-xs font-semibold uppercase tracking-[0.12em] text-teal" htmlFor="planner-group">Travelling with<select className="min-h-11 rounded-xl border border-border bg-background px-3 text-sm font-medium normal-case tracking-normal text-foreground outline-none focus:border-teal" defaultValue="" id="planner-group" name="group"><option disabled value="">Choose a group</option><option value="solo">Just me</option><option value="couple">Two of us</option><option value="group">A group</option></select></label><button className="min-h-11 rounded-xl bg-forest px-5 text-sm font-semibold text-white transition-colors hover:bg-forest-deep" type="submit">Start planning</button></form></section>;
}

export function PopularTreks() {
  return <section className="popular-treks-section border-y border-border bg-surface-muted" id="popular-treks"><div className="mx-auto max-w-6xl px-6 py-16 lg:px-10 lg:py-20"><SectionHeading eyebrow="POPULAR TREKS" title="Find Your Next Trail" description="From peaceful Himalayan walks to high-altitude adventures, discover journeys worth remembering." /><div className="popular-treks-grid mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{treks.map((trek, index) => <article className="popular-trek-card group flex h-full flex-col overflow-hidden rounded-3xl border border-border bg-surface shadow-sm transition duration-300 hover:-translate-y-1 hover:shadow-lg" key={trek.slug}><div className="trek-card-media">{trek.image ? <Image alt="" className="object-cover transition duration-500 group-hover:scale-105" fill sizes="(min-width: 1024px) 33vw, (min-width: 640px) 50vw, 100vw" src={trek.image} /> : <div aria-hidden="true" className={`trek-placeholder trek-placeholder-${(index % 4) + 1}`} />}</div><div className="flex flex-1 flex-col p-4 sm:p-5"><h3 className="text-lg font-semibold tracking-[-0.03em] text-forest-deep sm:text-xl">{trek.name}</h3>{trek.region ? <p className="mt-1.5 text-sm text-foreground/65">{trek.region}</p> : null}{trek.summary ? <p className="mt-2 text-sm leading-6 text-foreground/65">{trek.summary}</p> : null}<Link className="mt-4 inline-flex items-center gap-2 self-start text-sm font-semibold text-teal transition-colors hover:text-forest" href={`/treks/${trek.slug}`}>View Trek <span aria-hidden="true">↗</span></Link></div></article>)}</div><div className="mt-8 text-center"><Link className="inline-flex items-center gap-2 border-b border-teal/40 pb-1 text-sm font-semibold text-teal transition-colors hover:border-teal hover:text-forest" href="/treks">Explore All Treks <span aria-hidden="true">→</span></Link></div></div></section>;
}

export function ExperienceSection() {
  return <section className="experience-section border-y border-border bg-surface-muted"><div className="mx-auto max-w-6xl px-6 py-16 lg:px-10 lg:py-20"><SectionHeading eyebrow="EXPLORE YOUR WAY" title="Choose Your Kind of Adventure " description="From easy weekend escapes to snow-covered Himalayan trails, find a journey that fits your style." /><div className="experience-grid mt-8 grid gap-4 md:grid-cols-2 lg:grid-cols-3">{experiences.map((experience) => <article className="experience-card group flex h-full flex-col overflow-hidden rounded-3xl border border-border bg-white/80 shadow-sm transition duration-300 hover:-translate-y-1 hover:shadow-lg" key={experience.slug}><div aria-hidden="true" className={`experience-card-visual experience-card-visual-${experience.visual}`} /><div className="flex flex-1 items-end justify-between gap-3 p-4 sm:p-5"><div><h3 className="text-lg font-semibold tracking-[-0.03em] text-forest-deep sm:text-xl">{experience.name}</h3><p className="mt-1.5 max-w-sm text-sm leading-6 text-foreground/65">{experience.description}</p></div><Link aria-label={`Explore ${experience.name}`} className="inline-flex size-9 shrink-0 items-center justify-center rounded-full bg-forest text-base text-white transition-colors hover:bg-teal" href={experience.href}><span aria-hidden="true">↗</span></Link></div></article>)}</div></div></section>;
}

export function WhyTrekPhillic() {
  return <section className="mx-auto grid max-w-6xl gap-12 px-6 py-24 lg:grid-cols-[0.4fr_0.6fr] lg:items-start lg:px-10" id="why-trekphillic"><div><SectionHeading eyebrow="WHY TREKPHILLIC" title="More Than a Trip, It's an Experience." description="We believe travel should feel personal, thoughtfully planned, and worth remembering. From the trail you choose to the journey that gets you there, we keep the experience simple and meaningful." /><LinkButton className="mt-8" href="/about" variant="secondary">About TrekPhillic <span aria-hidden="true">→</span></LinkButton></div><div className="grid gap-3 sm:grid-cols-2">{valuePoints.map((point) => <article className="group rounded-2xl border border-white/60 bg-white/65 p-5 shadow-sm transition duration-300 hover:-translate-y-1 hover:border-teal/40 hover:shadow-md" key={point.title}><div className="flex items-start gap-4"><span aria-hidden="true" className="inline-flex size-9 shrink-0 items-center justify-center rounded-full border border-teal/35 text-xs font-semibold text-teal transition-colors group-hover:border-teal group-hover:bg-teal group-hover:text-white">{point.marker}</span><div><h3 className="font-semibold text-forest-deep">{point.title}</h3><p className="mt-2 text-sm leading-6 text-foreground/70">{point.description}</p></div></div></article>)}</div></section>;
}

export function TourPackages() {
  return <section className="tour-packages-section border-t border-border" id="tour-packages"><div className="mx-auto max-w-6xl px-6 py-16 lg:px-10 lg:py-20"><SectionHeading eyebrow="EXPLORE BEYOND THE TRAIL" title="Journeys Made for the Mountains" description="Go beyond the trek with thoughtfully planned mountain tours, scenic road journeys and customized travel experiences." /><div className="tour-packages-grid mt-8 grid gap-4 md:grid-cols-2 lg:grid-cols-3">{tourCategories.map((tour) => <article className="tour-package-card group flex h-full flex-col overflow-hidden rounded-3xl border border-white/65 bg-white/75 shadow-sm transition duration-300 hover:-translate-y-1 hover:shadow-lg" key={tour.slug}><div aria-hidden="true" className={`tour-card-visual tour-card-visual-${tour.visual}`} /><div className="flex flex-1 items-end justify-between gap-3 p-5"><div><h3 className="text-xl font-semibold tracking-[-0.03em] text-forest-deep">{tour.name}</h3><p className="mt-2 max-w-xl text-sm leading-6 text-foreground/70">{tour.description}</p></div><Link aria-label={`Explore ${tour.name}`} className="inline-flex shrink-0 items-center gap-2 text-sm font-semibold text-teal transition-colors hover:text-forest" href={tour.href}>Explore Tour <span aria-hidden="true">→</span></Link></div></article>)}</div></div></section>;
}
export function Vehicles() {
  return <section className="vehicle-section border-t border-border" id="vehicles"><div className="mx-auto max-w-6xl px-6 py-16 lg:px-10 lg:py-20"><SectionHeading eyebrow="TRAVEL YOUR WAY" title="Comfortable Rides for Mountain Journeys" description="From couples and families to larger groups, choose a vehicle that fits your journey." /><div className="vehicle-grid mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{vehicleCategories.map((vehicle) => <article className="vehicle-card group flex h-full flex-col overflow-hidden rounded-3xl border border-white/65 bg-white/75 shadow-sm transition duration-300 hover:-translate-y-1 hover:shadow-lg" key={vehicle.slug}><div aria-hidden="true" className={`vehicle-card-visual vehicle-card-visual-${vehicle.visual}`} /><div className="flex flex-1 flex-col p-4"><h3 className="text-lg font-semibold tracking-[-0.03em] text-forest-deep">{vehicle.name}</h3><p className="mt-1.5 text-sm leading-6 text-foreground/70">{vehicle.description}</p><Link aria-label={`Enquire about ${vehicle.name}`} className="mt-4 inline-flex items-center gap-2 self-start text-sm font-semibold text-teal transition-colors hover:text-forest" href={vehicle.href}>Enquire <span aria-hidden="true">→</span></Link></div></article>)}</div></div></section>;
}

export function TravellerStories() {
  return <section className="traveller-stories-section border-t border-border"><div className="mx-auto grid max-w-6xl items-center gap-8 px-6 py-16 lg:grid-cols-[0.9fr_1.1fr] lg:gap-14 lg:px-10 lg:py-20"><div aria-hidden="true" className="traveller-stories-visual"><span className="traveller-stories-sun" /><span className="traveller-stories-route" /><span className="traveller-stories-visual-label">A story begins here</span></div><div><SectionHeading eyebrow="TRAVELLERS SPEAK" title="Your Journey. Your Story." description="Every mountain journey creates a story worth remembering. Traveller stories and experiences will appear here as we begin creating them together." /><div className="mt-6 inline-flex items-center gap-2 rounded-full border border-teal/25 bg-white/60 px-3 py-1.5 text-xs font-semibold uppercase tracking-[0.12em] text-teal"><span aria-hidden="true" className="size-1.5 rounded-full bg-teal" />Stories coming soon</div><div><LinkButton className="mt-7 !text-white" href="/enquiry">Plan Your Journey <span aria-hidden="true" className="ml-2">→</span></LinkButton></div></div></div></section>;
}

export function CallToAction() {
  return <section className="final-cta-section bg-forest px-6 text-white lg:px-10" id="final-cta"><div className="mx-auto flex max-w-6xl flex-col justify-between gap-8 py-16 sm:flex-row sm:items-end lg:py-20"><div className="max-w-2xl"><Badge>READY TO EXPLORE?</Badge><h2 className="mt-5 text-4xl font-semibold tracking-[-0.04em] sm:text-5xl">Your Next Mountain Journey Starts Here.</h2><p className="mt-4 max-w-xl text-base leading-7 text-white/75">Tell us where you want to go, when you want to travel, and who you&apos;re travelling with. We&apos;ll help you plan the journey.</p></div><div className="flex flex-wrap items-center gap-5"><LinkButton className="shrink-0 bg-white !text-black hover:bg-sage" href="/enquiry">Send an Enquiry <span aria-hidden="true" className="ml-2">→</span></LinkButton><Link className="text-sm font-semibold text-white/80 transition-colors hover:text-white" href="/treks">Explore Treks</Link></div></div></section>;
}